### ISSUE TITLE
Android 上使用

### ISSUE THREAD

**Issue by pixiandouban** [metowolf/vCards#100]
不知道有没有人在 Android 上使用过，有段时间加入之后，联系人和短信都显示头像，最近不知道为什么，联系人头像正常，短信没有头像。

**Comment by magisk317** [comment]
请教下Android上怎么使用？解压后几百个文件一股脑导入吗？还是有办法导入订阅？

**Comment by qianjun2659** [comment]
用汇总目录-全部全部.vcf导入。

**Comment by TaivasJumala** [comment]
用 [DAVx⁵](https://www.davx5.com/) 可以添加账号
