### ISSUE TITLE
华住会

### ISSUE THREAD

**Issue by littlepanda0716** [metowolf/vCards#189]
- **类别**： 「出行购票」
 - **组织名称**：「华住会」
 - **电话号码**：「1069019879581」
 - **官方网址**：「http://www.huazhu.com」

**Comment by slgxmh** [comment]
号码收录
由于不同地区不同运营商的 106 短信推送号段存在差异，项目不作收录，建议将本项目作为一个基础模板，导入联系人后可以按以下方式自行补充其余号码

**Comment by slgxmh** [comment]
请看REAMME-号码收录
由于不同地区不同运营商的 106 短信推送号段存在差异，项目不作收录，建议将本项目作为一个基础模板，导入联系人后可以按以下方式自行补充其余号码
