### ISSUE TITLE
交通银行信用卡&哔哩哔哩&京东&中国农业银行&德邦物流&菜鸟裹裹&微医&EMS&微众银行&圆通速递

### ISSUE THREAD

**Issue by haozi99** [metowolf/vCards#197]
- **类别**： 「金融银行」
 - **组织名称**：「交通银行信用卡」
 - **电话号码**：「106909289888」
 - 「10692889888」
 - **官方网址**：「https://creditcard.bankcomm.com/content/index.html 」
 - **类别**： 「金融银行」
 - **组织名称**：「花呗」
 - **电话号码**：「106936957620040」
 - **官方网址**：「https://render.alipay.com/p/z/huabei-product-online/huabei-pc.html?user=forceDeprecated 」
 - **类别**： 「互联网」
 - **组织名称**：「哔哩哔哩」
 - **电话号码**：「1069376221174979112」
 - 「106806452123」
 - 「10692216791123」
 - 「10659024240000690642」
 - 「106940286684737109」
 - 「10691216436009」
 - 「118030478737109」
 - 「1069402851262749791」
 - 「10693716314874979112」
 - 「106827477274979112」
 - 「10692872314874979112」
 - 「1069287226274979112」
 - 「10693878436009」
 - 「106927470168651309」
 - 「106818253143874979112」
 - 「106807059836310709」
 - **官方网址**：「https://www.bilibili.com/ 」
 - **类别**： 「电商购物」
 - **组织名称**：「京东」
 - **电话号码**：「1069371626265380107」
 - 「10682583580196300」
 - 「1180700102627440」
 - 「10692357130096300」
 - 「10690557710」
 - 「106809386378」
 - 「106909122213066300」
 - 「106805352740096300」
 - 「1069351311370096300」
 - 「10691475301116693630」
 - 「1068053531403563011069376221135943909」
 - 「10659059518888635916」
 - 「118020628660146303」
 - 「10659024240000682062」
 - 「10691475301116693630」
 - 「1069402866300356301」
 - **官方网址**：「https://www.jd.com/ 」
 - **类别**： 「金融银行」
 - **组织名称**：「中国农业银行」
 - **电话号码**：「+86(10)69095599」
 - **官方网址**：「https://www.abchina.com/ 」
 - **类别**： 「快递物流」
 - **组织名称**：「德邦快递」
 - **电话号码**：「1181705431496608」
 - **官方网址**：「https://www.deppon.com/ 」
 - **类别**： 「快递物流」
 - **组织名称**：「菜鸟裹裹」
 - **电话号码**：「+86(576)81115449」
 - **官方网址**：「https://www.cainiao.com/ 」
 - **类别**： 「金融银行」
 - **组织名称**：「招商银行信用卡」
 - **电话号码**：「106590256211740」
 - **官方网址**：「http://cc.cmbchina.com/ 」
 -  - **类别**： 「其他」
 - **组织名称**：「微医」
 - **电话号码**：「106940286663226」
 - 「10681648022」
 - 「10691652022」
 - **官方网址**：「https://www.guahao.com/ 」
 - **类别**： 「快递物流」
 - **组织名称**：「EMS」
 - **电话号码**：「1069323011185」
 - 「1069127411185」
 - **官方网址**：「https://www.ems.com.cn/ 」
 - **类别**： 「金融银行」
 - **组织名称**：「微众银行」
 - **电话号码**：「1069119425921」
 - **官方网址**：「https://www.webank.com/#/home 」
 -  **类别**： 「快递物流」
 - **组织名称**：「圆通速递」
 - **电话号码**：「1180700103149737」
 - 「1180700831497370」
 - **官方网址**：「https://www.yto.net.cn/ 」
 -  **类别**： 「电商购物」
 - **组织名称**：「任你购」
 - **电话号码**：「106901576300111497」
 - **官方网址**：「https://rennigou.jp/ 」

**Comment by metowolf** [comment]
感谢提供，由于不同地区不同运营商的 106 短信推送号段存在差异，为避免基础模版膨胀，项目暂不作收录
