### ISSUE TITLE
丰巢 & 菜鸟裹裹

### ISSUE THREAD

**Issue by solarhell** [metowolf/vCards#2]
- **类别**： 快递物流
 - **组织名称**：丰巢
 - **电话号码**：10691184148605
 - **官方网址**：https://www.fcbox.com/

 - **类别**： 快递物流
 - **组织名称**：菜鸟裹裹
 - **电话号码**：
				10691491211900016
				1069223991395900016
				10655000218419507900
				1069330011900016
 - **官方网址**：https://www.guoguo-app.com/

**Comment by metowolf** [comment]
感谢提供，106 号码可以导入后根据个人情况自行添加
