### ISSUE TITLE
建议增加 LDAP 或者 CardDAV 订阅选项

### ISSUE THREAD

**Issue by krkrchan** [metowolf/vCards#208]
目前许多设备，如 iPhone，都有订阅 LDAP、CardDAV 账户功能。

希望能增加订阅链接功能，以供设备自动获取更新。

谢谢。

**Comment by Hao0920** [comment]
这个[issue](https://github.com/metowolf/vCards/issues/50) 最下面有个热心大佬制作了Radicale的vCards服务器，可以直接使用，自己搭建的话也有教程。
想Docker部署找[tomsquest/docker-radicale](https://github.com/tomsquest/docker-radicale)

另外还有一款[Baïkal](https://github.com/sabre-io/Baikal)，可搭建也有Docker，不像Radicale可以上传，需要搭配Thunderbird、eM使用。

**Comment by metowolf** [comment]
感谢 @dallaslu 提供的支持，项目现已提供 CardDAV 服务。

**Comment by gujiangjiang** [comment]
感觉各有好处，导入的好处是同终端同步，订阅不能多终端同步，需要每个终端分别订阅才行

**Comment by misaka-clover** [comment]
感谢！

**Comment by Liujunfeng75665260** [comment]
106的 快递号码什么时间能同步呢

**Comment by imvicchen** [comment]
订阅的抓取特别慢怎么办，Mac电脑两天抓了10几个号码

**Comment by imvicchen** [comment]
> 106的 快递号码什么时间能同步呢

同求～

**Comment by karlguo7** [comment]
大佬，我在iPhone上通讯录添加了CARDDAV账户，但是同步很慢，今天一上午只有83个账户同步过来了，请问怎么解决呢？![image](https://github.com/user-attachments/assets/d07fa323-027b-4c79-85c4-0dd85d884333)

**Comment by karlguo7** [comment]
> 大佬，我在iPhone上通讯录添加了CARDDAV账户，但是同步很慢，今天一上午只有83个账户同步过来了，请问怎么解决呢？![image](https://github.com/user-attachments/assets/d07fa323-027b-4c79-85c4-0dd85d884333)

@metowolf

**Comment by WhitCrow** [comment]
> > 大佬，我在iPhone上通讯录添加了CARDDAV账户，但是同步很慢，今天一上午只有83个账户同步过来了，请问怎么解决呢？![image](https://private-user-images.githubusercontent.com/83171435/391220555-d07fa323-027b-4c79-85c4-0dd85d884333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTUzNjIsIm5iZiI6MTczMzk5NTA2MiwicGF0aCI6Ii84MzE3MTQzNS8zOTEyMjA1NTUtZDA3ZmEzMjMtMDI3Yi00Yzc5LTg1YzQtMGRkODVkODg0MzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA5MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYTNiZGU4MWM1YjhlYWZmNWI0MzcwOTY0OGRiZTBkYjlmNGVhNDg1NjlkZGM0MmYzYjQyMjE1YTNhNTk1ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oiXKtowXe-5CRifWvDjZVzJvW8UTqnThYPjiO7IvY-4)
> 
> @metowolf

老哥解决了吗，我的也是，开不开全局代理更新都很慢，一天了，还是60条

**Comment by VectorZhao** [comment]
> 这个[issue](https://github.com/metowolf/vCards/issues/50) 最下面有个热心大佬制作了Radicale的vCards服务器，可以直接使用，自己搭建的话也有教程。 想Docker部署找[tomsquest/docker-radicale](https://github.com/tomsquest/docker-radicale)
> 
> 另外还有一款[Baïkal](https://github.com/sabre-io/Baikal)，可搭建也有Docker，不像Radicale可以上传，需要搭配Thunderbird、eM使用。

![image](https://github.com/user-attachments/assets/7e2123e8-dd2c-4395-a66b-fe4c82679615)
请问radicale如何才能创建分组，通过web上传都是一个vcf文件一个独立的组。

**Comment by bbcvc** [comment]
很慢，一天下去只有80几条

**Comment by funnyzak** [comment]
做一个Docker镜像，包含 GHCR 和 阿里云镜像。和源仓库自动同步数据。

大家嫌慢可以自己服务器部署。如下，每天零时进行版本检查并同步最新：

```bash
docker run -d --name vcard \
    -p 5232:5232 \
    -e SYNC_CRON="0 0 * * *" \
    funnyzak/vcards:latest
```

启动后，使用方式和官方一样。

**Comment by VectorZhao** [comment]
> ```shell
> docker run -d --name vcard \
>     -p 5232:5232 \
>     -e SYNC_CRON="0 0 * * *" \
>     funnyzak/vcards:latest
> ```
手动点赞👍

**Comment by VectorZhao** [comment]
> 做一个Docker镜像，包含 GHCR 和 阿里云镜像。和源仓库自动同步数据。
> 
> 大家嫌慢可以自己服务器部署。如下，每天零时进行版本检查并同步最新：
> 
> ```shell
> docker run -d --name vcard \
>     -p 5232:5232 \
>     -e SYNC_CRON="0 0 * * *" \
>     funnyzak/vcards:latest
> ```
> 
> 启动后，使用方式和官方一样。

没有分组，mac上就拉取了这么多
![image](https://github.com/user-attachments/assets/47cb7769-5763-4cb2-89c7-d4ec1d8ca71d)

**Comment by funnyzak** [comment]
> > 做一个Docker镜像，包含 GHCR 和 阿里云镜像。和源仓库自动同步数据。
> > 大家嫌慢可以自己服务器部署。如下，每天零时进行版本检查并同步最新：
> > ```shell
> > docker run -d --name vcard \
> >     -p 5232:5232 \
> >     -e SYNC_CRON="0 0 * * *" \
> >     funnyzak/vcards:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 启动后，使用方式和官方一样。
> 
> 没有分组，mac上就拉取了这么多 ![image](https://private-user-images.githubusercontent.com/16644993/396422080-47cb7769-5763-4cb2-89c7-d4ec1d8ca71d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjUyNjksIm5iZiI6MTczNDQyNDk2OSwicGF0aCI6Ii8xNjY0NDk5My8zOTY0MjIwODAtNDdjYjc3NjktNTc2My00Y2IyLTg5YzctZDRlYzFkOGNhNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGExNTEzZjcyNzMxMmE1MWI3ZGU3M2NiYjYyMTVlYmQ5NmQ3NjhhNGEzMTFmZGU4YjdhYWU1YTM0ZDJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VaNsuzL8EM9Saxx6hyJFyu2h8y-GILUoc4DGVhKXDPA)

Mac上我没试，手机上没问题，如下:
![contact](https://github.com/user-attachments/assets/d1557e12-655d-4173-93af-9843e51bf78c)

**Comment by VectorZhao** [comment]
手机确实没有问题，感谢制作的docker

**Comment by debugAllTheTime** [comment]
请问docker服务器弄好了手机上是设置为：
服务器：IP
用户名：cn
高级设置：
使用ssl：否
端口：5232
账户url：
http://ip:5232
吗？

**Comment by VectorZhao** [comment]
> 请问docker服务器弄好了手机上是设置为： 服务器：IP 用户名：cn 高级设置： 使用ssl：否 端口：5232 账户url： http://ip:5232 吗？

必须是域名，ip 端口应该是不可以

**Comment by debugAllTheTime** [comment]
好的。谢谢！

**Comment by WhitCrow** [comment]
> > 请问docker服务器弄好了手机上是设置为： 服务器：IP 用户名：cn 高级设置： 使用ssl：否 端口：5232 账户url： http://ip:5232 吗？
> 
> 必须是域名，ip 端口应该是不可以

怪不得，配置了半天显示账号密码错误

**Comment by langchao123G** [comment]
Mac 上提示无法验证用户名和密码

**Comment by langchao123G** [comment]
> 订阅的抓取特别慢怎么办，Mac电脑两天抓了10几个号码

Mac电脑提示 无法验证用户名和密码，请问是怎么添加的呢

**Comment by DejaVuDarren** [comment]
> 做一个Docker镜像，包含 GHCR 和 阿里云镜像。和源仓库自动同步数据。
> 
> 大家嫌慢可以自己服务器部署。如下，每天零时进行版本检查并同步最新：
> 
> ```shell
> docker run -d --name vcard \
>     -p 5232:5232 \
>     -e SYNC_CRON="0 0 * * *" \
>     funnyzak/vcards:latest
> ```
> 
> 启动后，使用方式和官方一样。

这个怎么搞呀？谁能教一下。

**Comment by DejaVuDarren** [comment]
> 请问docker服务器弄好了手机上是设置为： 服务器：IP 用户名：cn 高级设置： 使用ssl：否 端口：5232 账户url： http://ip:5232 吗？



这个在IPhone哪里设置呀？

**Comment by HUGOrabit** [comment]
耐克，极氪的logo是黑色的，因为通讯录背景是黑色的，所以显示不出来，建议把这种图标增加个背景颜色。

**Comment by jinliming2** [comment]
这里记录个问题：

昨天在本地自建，发现 iOS 添加 CardDAV 在配置不使用 SSL 的时候，不会发送凭据验证信息，导致 radicale 服务一直返回 `401`，无法验证账号密码。
后面搞了个自签名证书，开启 SSL 再添加就正常了。自签名证书在添加的时候会弹出提示信任的弹窗。

**Comment by tshu-w** [comment]
> 没有分组，mac上就拉取了这么多 ![image](https://github.com/user-attachments/assets/47cb7769-5763-4cb2-89c7-d4ec1d8ca71d)

发现貌似是因为 macOS 不支持 multiple collections，默认只拉了第一个文件夹：
https://discussions.apple.com/thread/6612054?sortBy=rank
https://central.owncloud.org/t/owncloud-9-1-1-1-2-macos-sierra-carddav-not-working-solved/3481/24

**Comment by XieYe9909** [comment]
> https://central.owncloud.org/t/owncloud-9-1-1-1-2-macos-sierra-carddav-not-working-solved/3481/24

我的也是这样，请问有解决方法吗？
