### ISSUE TITLE
建议添加各银行信用卡电话及短信

### ISSUE THREAD

**Issue by Mosney** [metowolf/vCards#28]
信用卡电话一般都是400电话，部分银行还有VIP专线，  
另外银行的短信号码一般都是固定的1069xx+955xx，所以银行业可以考虑添加短信1069号码

**Comment by metowolf** [comment]
感谢建议，后续会对银行信用卡号码进行补充。

至于 106 号段，部分企业使用的号段有固定后缀格式，如：

 - 中国银行：95566；106590202**95566** 等 26 个
 - 交通银行：95559；106900**9888**；106907**9888** 等 10 个
 - 中国农业银行：95599；10690**95599**
 - 阿里云：95187；106590256211**9757920**；106590256200**9757920** 等 60 个

虽然能够枚举收录所有号码，但不同地区的推送号码相对固定，为了保持通讯录的条目精简，因此 106 号码统一不作收录。

**Comment by hahadoudouhaha** [comment]
点哪里下载，菜鸟研究了半天😂

**Comment by hahadoudouhaha** [comment]
找不到打包文件下载链接

**Comment by hahadoudouhaha** [comment]
找到了

**Comment by Ivysauro** [comment]
我觉得没必要，尤其是对安装了短信过滤app的iOS用户，因为Apple现在的机制是**不过滤**通讯录里的号码

**Comment by Mosney** [comment]
> 我觉得没必要，尤其是对安装了短信过滤app的iOS用户，因为Apple现在的机制是**不过滤**通讯录里的号码（银行很多106号码都是干扰性信息）

银行不会发太多垃圾短信的，你收到的那些106垃圾短信都不是银行发的，盲猜你是天天收到自称是各银行给你发的邀请办卡短信这种短信

**Comment by MisterGlasses** [comment]
@Ivysauro我把vcard群组隐藏掉 短信过虑app也不会过滤联系人发的短信吗
