### ISSUE TITLE
看到麻烦请您回复一下

### ISSUE THREAD

**Issue by Veeziie** [metowolf/vCards#288]
在微信公众号里有人使用您这个脚本，iPhone上快捷指令一键添加的。可是批量添加完以后也并没有显示，请问该如何删除刚刚添加过的东西呢。

https://user-images.githubusercontent.com/132649712/236401592-b9382f3e-e931-4e24-8500-6b65921f3594.mp4

[https://www.icloud.com/shortcuts/f49f6f5d974247378c20cbead7ecf5a4](url)

**Comment by metowolf** [comment]
导入后的数据可以在通讯录联系人分组中查看到，从视频中看并没有成功导入，只是预览了一下

**Comment by Veeziie** [comment]
谢谢您的回复


张帆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metowolf/vCards"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metowolf/vCards] 看到麻烦请您回复一下 (Issue #288)





 
导入后的数据可以在通讯录联系人分组中查看到，从视频中看并没有成功导入，只是预览了一下
