### ISSUE TITLE
96533 这个号码挺多机构使用的

### ISSUE THREAD

**Issue by LisonFan** [metowolf/vCards#313]
目前我看库里把96533分配给了富滇银行，可能需要调整一下，加上区号

 - **类别**： 金融银行
 - **组织名称**：富滇银行
 - **电话号码**：`0871-96533` `4008896533`
 - **官方网址**：https://www.fudian-bank.com
---

 - **类别**： 本地生活
 - **组织名称**：长沙水业集团
 - **电话号码**：`0731-96533`
 - **官方网址**：http://www.supplywater.com
 ---
 - **类别**： 本地生活
 - **组织名称**：粤通卡
 - **电话号码**：`020-96533`
 - **官方网址**：https://www.96533.com 
---

- `贵州省市场监管局96533电梯应急救援处置指挥中心` https://www.sohu.com/a/585882513_121106687
- `广东省高速公路出行服务热线` https://baijiahao.baidu.com/s?id=1749022768112129076&wfr=spider&for=pc

**Comment by metowolf** [comment]
感谢提醒，已对「富滇银行」条目修正
