### ISSUE TITLE
可以做个骚扰电话的vCards导入手机直接拉黑那个联系人

### ISSUE THREAD

**Issue by youzengwei** [metowolf/vCards#32]
- **类别**： 「骚扰电话」
 - **组织名称**：「这里填写公司组织的名称」
 - **电话号码**：「这里填写电话，如有多个请分行填写」
 - **官方网址**：「这里填写官方网址」

**Comment by metowolf** [comment]
骚扰电话直接使用「阻止此来电号码」功能即可，好像没有必要单独拉一个联系人出来？
