### ISSUE TITLE
汇丰银行补充上海区号

### ISSUE THREAD

**Issue by HUANGvia** [metowolf/vCards#327]
- **类别**： 「金融机构」
 - **组织名称**：「汇丰银行」
 - **电话号码**：「(021) 95366」
 - **官方网址**：「(https://www.hsbc.com.cn/)」

**Comment by DieMagithub** [comment]
建议关闭。此号码不仅存在于上海，至少在北京也可以不加区号打通。
或者也可以反过来说，每个95开头的号码都应该加上所有支持的区号，以便“在北京想和上海的客服谈谈”的问题。

**Comment by metowolf** [comment]
额外区号需求可以通过添加到已有联系人方式解决，此 issue 先关闭
