### ISSUE TITLE
强烈建议在release包里增加一个“以上全部”

### ISSUE THREAD

**Issue by s7lx** [metowolf/vCards#37]
强烈建议在release包里增加一个“以上全部”
这样就不用一个一个导入了

**Comment by skychx** [comment]
vcard 有大小限制，最大大小为 256 KB，这个可能搞不了

**Comment by skychx** [comment]
> 强烈建议在release包里增加一个“以上全部”
> 这样就不用一个一个导入了

vcard 有大小限制，最大大小为 256 KB，这个可能搞不了

**Comment by tanglueyi** [comment]
小tip：在Mac上可以全选然后拖放在通讯录窗口可以实现全部导入

**Comment by metowolf** [comment]
已经添加，可在压缩包内 `汇总/全部.vcf` 找到
