### ISSUE TITLE
新增汇丰银行（中国）

### ISSUE THREAD

**Issue by misaka-clover** [metowolf/vCards#404]
- **类别**： 「金融银行」
 - **组织名称**：「汇丰银行（中国）」
 - **电话号码**：「95366」
 - **官方网址**：「https://www.hsbc.com.cn 」

**Comment by YuruiHong** [comment]
你提交的号码表示方法似乎和`yarn test`中规定的格式不符，建议将香港区号写成`+852 <号码>`的格式，且后方号码内部无空格。

**Comment by misaka-clover** [comment]
你好，我已修改号码区号为 +852，也删除了号码中的空格。可是我不知道「在根目录下执行 `yarn test` 检查格式规范」这一步应该怎么做，请问可以指导一下吗？
