### ISSUE TITLE
是不是可以弄成一个订阅呢？

### ISSUE THREAD

**Issue by deepfish** [metowolf/vCards#50]
当前 iOS 设备支持“CardDAV” 和 “LDAP” 方式订阅通讯录，弄成这两种模式是不是会比较方便呢？云端更新后，自动同步到本地。

**Comment by vicliu1990** [comment]
没找到订阅功能， ls在哪里看到的？

**Comment by metowolf** [comment]
目前项目不对 106 号码进行收录，如果使用订阅方式似乎会直接覆盖掉本地改动？

**Comment by Jinkeycode** [comment]
已支持自动导入，还没上架，可以先在 testfight 下载 [https://testflight.apple.com/join/FLmIVCBU](https://testflight.apple.com/join/FLmIVCBU)

![image](https://user-images.githubusercontent.com/12148377/61349354-5d933500-a896-11e9-8b90-7c552ad02a98.png)

**Comment by Leeiio** [comment]
@Jinkeycode 无法申请

**Comment by Jinkeycode** [comment]
@Leeiio 忘记点通知测试员了，现在可以了

**Comment by deepfish** [comment]
106 短信可否讓用戶參與呢？雲端先做收錄，然後定期更新。

**Comment by deepfish** [comment]
> @Leeiio 忘记点通知测试员了，现在可以了

106 短信可否讓用戶參與呢？雲端先做收錄，然後定期更新。

**Comment by Jinkeycode** [comment]
@deepfish 这个仓库的作者好像不赞成加入106的号码，等作者看到跟我联系一下再讨论一下吧，他的个人博客打不开，找不到联系方式。

**Comment by luojianxhlxt** [comment]
> 已支持自动导入，可以在 App Store下载 [iOS 版本](https://apps.apple.com/cn/app/id1472985737) 或者酷安 [Android 版](https://www.coolapk.com/apk/238353)
> 
> ![image](https://user-images.githubusercontent.com/12148377/61539512-4444e100-aa6e-11e9-8a0d-0fa52cecb23c.png)

这个app有一个建议
希望添加的企业名字，用的字段都是"公司"字段，而不是"名"字段
在群里反馈没有回应，就在这里反馈一下了

**Comment by MisterGlasses** [comment]
我们在补充时 将补充或改动新建联系人到本机就好了

**Comment by liyishuai** [comment]
> 目前项目不对 106 号码进行收录，如果使用订阅方式似乎会直接覆盖掉本地改动？

订阅数据属于单独的“目录”，与本地联系人是平行关系，不会覆盖。

**Comment by dallaslu** [comment]
用 Radicale 搭一个 CardDav Server？

**Comment by LuzMasonj** [comment]
这个在线订阅还有可能实现吗

**Comment by dallaslu** [comment]
> 这个在线订阅还有可能实现吗

一定会有哒

**Comment by dallaslu** [comment]
> 这个在线订阅还有可能实现吗
已经实现啦：https://dallas.lu/radicale-server-for-vcards

**Comment by LuzMasonj** [comment]
> > 这个在线订阅还有可能实现吗
> 
> 已经实现啦：https://dallas.lu/radicale-server-for-vcards

按教程填了 好像不能用啊

**Comment by luojianxhlxt** [comment]
> > 这个在线订阅还有可能实现吗
> 
> 已经实现啦：https://dallas.lu/radicale-server-for-vcards

等待热心群众提供公开服务呀

**Comment by DAVPanda** [comment]
> > 这个在线订阅还有可能实现吗
> 
> 已经实现啦：https://dallas.lu/radicale-server-for-vcards

2022.1.6测试不能正常使用，期待热心群众提供一个订阅

**Comment by dallaslu** [comment]
热心群众终于到位了！以 iOS 为例：

> 
> `设置>邮件>账户>添加账户>其他>（通讯录）添加 CardDAV 账户`：
> 
> * 服务器： `vcards.1bps.cn` (或 `https://vcards.1bps.cn`)
> * 用户名： `cn`
> * 密码：任意填写
> * 描述：任意填写（因为 iOS 的 Bug，并不能随时修改，建议填写为「中国黄页」）
>
> 点击右上存储，在接下来弹出的提示中选择「保留通讯录」。

cc: @DAVPanda @luojianxhlxt @LuzMasonj

**Comment by luojianxhlxt** [comment]
> 热心群众终于到位了！以 iOS 为例：
> 
> > `设置>邮件>账户>添加账户>其他>（通讯录）添加 CardDAV 账户`：
> > 
> > * 服务器： `vcards.1bps.cn` (或 `https://vcards.1bps.cn`)
> > * 用户名： `cn`
> > * 密码：任意填写
> > * 描述：任意填写（因为 iOS 的 Bug，并不能随时修改，建议填写为「中国黄页」）
> > 
> > 点击右上存储，在接下来弹出的提示中选择「保留通讯录」。
> 
> cc: @DAVPanda @luojianxhlxt @LuzMasonj

Thanks!

**Comment by DAVPanda** [comment]
> 热心群众终于到位了！以 iOS 为例：
> 
> > `设置>邮件>账户>添加账户>其他>（通讯录）添加 CardDAV 账户`：
> > 
> > * 服务器： `vcards.1bps.cn` (或 `https://vcards.1bps.cn`)
> > * 用户名： `cn`
> > * 密码：任意填写
> > * 描述：任意填写（因为 iOS 的 Bug，并不能随时修改，建议填写为「中国黄页」）
> > 
> > 点击右上存储，在接下来弹出的提示中选择「保留通讯录」。
> 
> cc: @DAVPanda @luojianxhlxt @LuzMasonj

首先感谢！之前尝试了不行的情况下我换了一个方法，把通讯录导入Google通讯录，然后在：设置>邮件>账户>添加账户中登录Google账户，然后开启通讯录同步，最后在通讯录分组中关闭显示Google通讯录群组。
这个方法适用于日常不使用Google通讯录的人，或者另外申请一个账号单独作为黄页通讯录也是可以的。优点是可以自己选择上传自己需要的通讯录列表，缺点就是没有科学上网工具的话不太好同步更新。
理论上来说Outlook通讯录也是可以实现的，但是我还没有实测过。

**Comment by dallaslu** [comment]
> 通讯录导入Google通讯录

我以前是导入到 iCloud 通讯录，然后建立了一个「黄页」分组。

订阅的方式，有两个问题：

1. 本来是可以在同步设置里自己指定分组的，但是 iOS 未提供此功能。
2. 公开订阅不提供写权限，无法自行直接编辑联系人。

虽然 iOS 不能选择订阅通讯录的同步分组，好在可以选择分组显示，仅浪费了一点点同步流量，不影响使用体验。

虽然无法直接编辑，但 iOS 会自动合并（链接）联系人进行展示。所以，若要添加 106 号码，可以自建同号码联系人进行编辑，iOS 会把两个同号联系人的所有字段合并显示为一个联系人。

**Comment by DAVPanda** [comment]
> > 通讯录导入Google通讯录
> 
> 我以前是导入到 iCloud 通讯录，然后建立了一个「黄页」分组。
> 
> 订阅的方式，有两个问题：
> 
> 1. 本来是可以在同步设置里自己指定分组的，但是 iOS 未提供此功能。
> 2. 公开订阅不提供写权限，无法自行直接编辑联系人。
> 
> 虽然 iOS 不能选择订阅通讯录的同步分组，好在可以选择分组显示，仅浪费了一点点同步流量，不影响使用体验。
> 
> 虽然无法直接编辑，但 iOS 会自动合并（链接）联系人进行展示。所以，若要添加 106 号码，可以自建同号码联系人进行编辑，iOS 会把两个同号联系人的所有字段合并显示为一个联系人。

用iCloud有一个问题很蛋疼，不仅需要建立一个黄页分组，还要建立一个自己的联系人分组，然后只显示自己的联系人分组，但是每次新建联系人都是保存至默认的所有联系人里，还需要手动添加到需要自己的联系人分组。
另外问一下订阅了这个CardDAV通讯录，我在本地修改联系人信息，比如给中国移动添加一个号码会同步到服务器吗？不同步的话再次更新会不会删除我添加的这个号码。

**Comment by dallaslu** [comment]
> 我在本地修改联系人信息，比如给中国移动添加一个号码会同步到服务器吗？

为了提供公开订阅服务，Radicale 是关闭了写权限的，所以……按我的使用经验，iOS 甚至不允许编辑只读联系人。所以也就不会同步到服务器。若是其他客户端允许修改，就有可能多次尝试进行同步，但都不会成功，浪费电池浪费流量。

如果是自建 Radicale，理论上是可以开写权限，不过联系人数据最终还是来自于 vCards 项目，若未来 vCards 发布新版，重新生成数据时还是会覆盖自建 Radicale 上的联系人的。如果放弃未来与 vCards 保持一致，自建 Radicale 可以开写权限，也就支持本地修改后再同步到服务器了。

> 不同步的话再次更新会不会删除我添加的这个号码

这个没试过（可能需要先开写权限>导入后断网>本地编辑联系人>再关闭写权限>尝试同步），不确定。取决于客户端实现。

如果放弃与订阅服务保持同步，可以在 iOS 导入后删除订阅账户并保留通讯录（仅以订阅服务为快速导入手机通讯录的途径而已）（获取还需要服务器开放写权限以允许 iOS 编辑联系人），这样就绝不会删除自行添加的号码。

综上，所以还是在 iOS 上自建同号联系人吧，简单有效。

**Comment by DAVPanda** [comment]
感谢解答，这个服务挺方便的。算是iOS黄页的另类实现方式，不过相比国内各大厂系统体验还是差很多。
