### ISSUE TITLE
中国移动手机报

### ISSUE THREAD

**Issue by tudi1909** [metowolf/vCards#54]
- **类别**： 「其它」
 - **组织名称**：「中国移动手机报」
 - **电话号码**：「10658000」
 - **官方网址**：「http://www.10086.cn/」

**Comment by metowolf** [comment]
感谢提供。
106 号码不做收录，另外「中国移动手机报」可以归类在「通讯服务 - 中国移动」下。

**Comment by tudi1909** [comment]
收到 感谢！
