### ISSUE TITLE
请求添加 中原银行

### ISSUE THREAD

**Issue by wao1201** [metowolf/vCards#59]
- **类别**： 「金融银行」
 - **组织名称**：「中原银行」
 - **电话号码**：「95186」
 - **官方网址**：「http://www.zybank.com.cn/」

**Comment by wao1201** [comment]
Logo: http://m.bangrong.com/data/upload/portal/2018/201808/20180808/5b6aa3afd25c6.jpg

**Comment by metowolf** [comment]
感谢提供
