### ISSUE TITLE
沃留言

### ISSUE THREAD

**Issue by DIYgod** [metowolf/vCards#6]
- **类别**： 通讯服务
 - **组织名称**：中国联通
 - **电话号码**：10165
 - **官方网址**：https://wly.mail.wo.cn

**Comment by metowolf** [comment]
感谢提供，未能提取有效 logo，先合并到中国联通下面。

**Comment by DIYgod** [comment]
或者可以直接用微信公众号的 logo？

![](https://i.loli.net/2019/06/20/5d0b5792e6c3a47324.jpg)
