### ISSUE TITLE
iOS 如何创建黄页分组？

### ISSUE THREAD

**Issue by lgatuk** [metowolf/vCards#62]
如何把所有的电话都存入黄页分组？谢谢。

**Comment by metowolf** [comment]
目前来看可能只能在 iCloud 上设置分组

**Comment by lgatuk** [comment]
能在iCloud 上批量导入您那个包吗？

**Comment by metowolf** [comment]
可以参考 https://support.apple.com/kb/ph3605?locale=zh_CN 导入

**Comment by lgatuk** [comment]
在web的iCloud上创建了分组，如何批量导入呢？只能一个个的vcf导入吗？

**Comment by lgatuk** [comment]
看到了，有个 全部.vcf
谢啦
（删除不太好删啦）
