### ISSUE TITLE
可以在联系人中隐藏吗

### ISSUE THREAD

**Issue by MisterGlasses** [metowolf/vCards#84]
ios上可以在联系人中隐藏吗 只在收到短信或电话时显示就行

**Comment by metowolf** [comment]
可以通过隐藏分组实现

**Comment by MisterGlasses** [comment]
能告知我一下怎么隐藏吗


________________________________
发件人: METO <notifications@github.com>
发送时间: 星期四, 九月 19, 2019 09:25
收件人: metowolf/vCards
抄送: Mr.Glasses; Author
主题: Re: [metowolf/vCards] 可以在联系人中隐藏吗 (#84)


可以通过隐藏分组实现

―

**Comment by metowolf** [comment]
首先在 iCloud 或者 Mac 上新建分组，然后导入/移动联系人到该分组中，就可以在一起iOS 联系人左上角群组中选择显示和隐藏了

**Comment by MisterGlasses** [comment]
谢谢 一会试一下


________________________________
发件人: METO <notifications@github.com>
发送时间: 星期四, 九月 19, 2019 09:32
收件人: metowolf/vCards
抄送: Mr.Glasses; Author
主题: Re: [metowolf/vCards] 可以在联系人中隐藏吗 (#84)


首先在 iCloud 或者 Mac 上新建分组，然后导入/移动联系人到该分组中，就可以在一起iOS 联系人左上角群组中选择显示和隐藏了

―
