### ISSUE TITLE
中国移动的号码为什么是1008611？

### ISSUE THREAD

**Issue by tanglueyi** [metowolf/vCards#85]
![image](https://user-images.githubusercontent.com/3315564/65214163-84aaf480-dadb-11e9-813e-56697918f5bb.png)
![image](https://user-images.githubusercontent.com/3315564/65214169-8d9bc600-dadb-11e9-9e86-7890dce54c5f.png)

**Comment by metowolf** [comment]
是有两个的，10086 和 1008611
